---
title: "Annual VMT"
---

```{r}
#| label: setup
#| include: false

library(dplyr)

data_url <- "https://cdn.jsdelivr.net/gh/vehicletrends/data@main/data/mileage_powertrain_type.csv"
mileage_data <- read.csv(data_url)
```

::: {.panel-tabset}

## Charts

```{r}
#| echo: false

htmltools::tags$iframe(
  src = 'https://019ba194-a0c8-3e09-1fa6-60ad0c332cb6.share.connect.posit.cloud/',
  width = "100%",
  height = "800",
  scrolling = "no",
  seamless = "seamless",
  frameBorder = "0"
)
```

## Data

<center>
[Download data](https://cdn.jsdelivr.net/gh/vehicletrends/data@main/data/mileage_powertrain_type.csv)

<div style="width:700px">

```{r}
mileage_data |>
  mutate(
    mileage_predicted = round(mileage_predicted, 0),
    age_years = round(age_years, 1)
  ) |>
  rename(
    Powertrain = powertrain,
    `Vehicle Type` = vehicle_type,
    `Age (years)` = age_years,
    `Predicted Mileage` = mileage_predicted
  ) |>
  reactable::reactable(
    searchable = TRUE,
    highlight = TRUE,
    filterable = TRUE,
    defaultPageSize = 10,
    showPageSizeOptions = TRUE,
    pageSizeOptions = c(5, 10, 25, 50)
  )
```

</div>
</center>

:::
