---
title: "Daily VMT"
---

```{r}
#| label: setup
#| include: false

library(dplyr)

data_url <- "https://cdn.jsdelivr.net/gh/vehicletrends/data@main/data/quantiles_dvmt.csv"
quantiles_dvmt <- read.csv(data_url)
```

::: {.panel-tabset}

## Charts

```{r}
htmltools::tags$iframe(
  src = 'https://019ba18d-a0d1-7762-3da9-bc57e4f3c0d8.share.connect.posit.cloud/',
  width = "100%",
  height = "800",
  scrolling = "no",
  seamless = "seamless",
  frameBorder = "0"
)
```

## Data

<center>
[Download data](https://cdn.jsdelivr.net/gh/vehicletrends/data@main/data/quantiles_dvmt.csv)

<div style="width:700px">

```{r}
quantiles_dvmt |>
  mutate(
    powertrain = case_when(
      powertrain == "all" ~ "All",
      powertrain == "bev" ~ "BEV",
      powertrain == "bev_non_tesla" ~ "BEV (non-Tesla)",
      powertrain == "bev_tesla" ~ "BEV (Tesla)",
      powertrain == "phev" ~ "PHEV",
      powertrain == "hev" ~ "HEV",
      powertrain == "cv" ~ "Conventional Vehicle",
      TRUE ~ powertrain
    )
  ) |>
  mutate(
    dvmt = round(dvmt, 2)
  ) |>
  rename(
    Powertrain = powertrain,
    `Vehicle Type` = vehicle_type,
    Quantile = quantile,
    DVMT = dvmt
  ) |>
  reactable::reactable(
    searchable = TRUE,
    highlight = TRUE,
    filterable = TRUE,
    defaultPageSize = 10,
    showPageSizeOptions = TRUE,
    pageSizeOptions = c(5, 10, 25, 50)
  )
```

</div>
</center>

:::
