---
title: "Dealership inventories"
---

```{r}
#| label: setup
#| include: false

library(dplyr)

data_url <- "https://cdn.jsdelivr.net/gh/jhelvy/vehicletrends@main/data/p_one_powertrain_vehicle_type.csv"
dealer_data <- read.csv(data_url)
```

::: {.panel-tabset}

## Charts

```{r}
#| echo: false

htmltools::tags$iframe(
  src = 'https://019ba1a1-6798-c19f-7482-1f96111440cd.share.connect.posit.cloud/',
  width = "100%",
  height = "800",
  scrolling = "no",
  seamless = "seamless",
  frameBorder = "0"
)
```

## Data

<center>
<a href="https://cdn.jsdelivr.net/gh/jhelvy/vehicletrends@main/data/p_one_powertrain_vehicle_type.csv" style="display: inline-block; padding: 8px 16px; background-color: #0066cc; color: white; text-decoration: none; border-radius: 4px; margin-bottom: 10px;">Download data</a>

<div style="width:700px">

```{r}
#| echo: false

dealer_data |>
  mutate(
    p = round(p, 3)
  ) |>
  rename(
    Powertrain = powertrain,
    `Vehicle Type` = vehicle_type,
    `Listing Year` = listing_year,
    `Percentage` = p
  ) |>
  reactable::reactable(
    searchable = TRUE,
    highlight = TRUE,
    filterable = TRUE,
    defaultPageSize = 10,
    showPageSizeOptions = TRUE,
    pageSizeOptions = c(5, 10, 25, 50)
  )
```

</div>
</center>

:::


