---
title: "Depreciation"
---

```{r}
#| label: setup
#| include: false

library(dplyr)

data_url <- "https://raw.githubusercontent.com/vehicletrends/vehicletrends/refs/heads/main/data-raw/depreciation_powertrain_type.csv"
depreciation_data <- read.csv(data_url)
```

::: {.panel-tabset}

## Charts

```{r}
#| echo: false

htmltools::tags$iframe(
  src = 'https://019ba196-b520-13ed-4198-caed05339ae5.share.connect.posit.cloud/',
  width = "100%",
  height = "800",
  scrolling = "no",
  seamless = "seamless",
  frameBorder = "0"
)
```

## Data

<center>
[Download data](https://raw.githubusercontent.com/vehicletrends/vehicletrends/refs/heads/main/data-raw/depreciation_powertrain_type.csv)

<div style="width:700px">

```{r}
depreciation_data |>
  mutate(
    rr_predicted = round(rr_predicted, 3),
    age_years = round(age_years, 1)
  ) |>
  rename(
    Powertrain = powertrain,
    `Vehicle Type` = vehicle_type,
    `Age (years)` = age_years,
    `Retention Rate` = rr_predicted
  ) |>
  reactable::reactable(
    searchable = TRUE,
    highlight = TRUE,
    filterable = TRUE,
    defaultPageSize = 10,
    showPageSizeOptions = TRUE,
    pageSizeOptions = c(5, 10, 25, 50)
  )
```

</div>
</center>

:::
