---
title: "Listings"
---

```{r}
#| label: setup
#| include: false

library(dplyr)

data_url <- "https://cdn.jsdelivr.net/gh/jhelvy/vehicletrends@main/data/p_market_powertrain_vehicle_type.csv"
market_data <- read.csv(data_url)
```

::: {.panel-tabset}

## Charts

```{r}
#| echo: false

htmltools::tags$iframe(
  src = 'https://019ba449-85f2-39ba-7c5f-a0a381c228e2.share.connect.posit.cloud/',
  width = "100%",
  height = "800",
  scrolling = "no",
  seamless = "seamless",
  frameBorder = "0"
)
```

## Data

<center>
[Download data](https://cdn.jsdelivr.net/gh/jhelvy/vehicletrends@main/data/p_market_powertrain_vehicle_type.csv)

<div style="width:700px">

```{r}
#| echo: false

market_data |>
  mutate(
    year_2018 = round(year_2018, 3),
    year_2024 = round(year_2024, 3)
  ) |>
  rename(
    Powertrain = powertrain,
    `Vehicle Type` = vehicle_type,
    `2018 Share` = year_2018,
    `2024 Share` = year_2024
  ) |>
  reactable::reactable(
    searchable = TRUE,
    highlight = TRUE,
    filterable = TRUE,
    defaultPageSize = 10,
    showPageSizeOptions = TRUE,
    pageSizeOptions = c(5, 10, 25, 50)
  )
```

</div>
</center>

:::


